[2024-01-31T09:17:44.702+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: classification_basic_1.evaluation manual__2024-01-31T09:17:21.156813+00:00 [queued]>
[2024-01-31T09:17:44.716+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: classification_basic_1.evaluation manual__2024-01-31T09:17:21.156813+00:00 [queued]>
[2024-01-31T09:17:44.717+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-01-31T09:17:44.740+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): evaluation> on 2024-01-31 09:17:21.156813+00:00
[2024-01-31T09:17:44.761+0000] {standard_task_runner.py:60} INFO - Started process 768 to run task
[2024-01-31T09:17:44.765+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'classification_basic_1', 'evaluation', 'manual__2024-01-31T09:17:21.156813+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/imt/classification_simple_demo/classification_simple.py', '--cfg-path', '/tmp/tmpwu_29aob']
[2024-01-31T09:17:44.766+0000] {standard_task_runner.py:88} INFO - Job 23: Subtask evaluation
[2024-01-31T09:17:44.839+0000] {task_command.py:423} INFO - Running <TaskInstance: classification_basic_1.evaluation manual__2024-01-31T09:17:21.156813+00:00 [running]> on host 4e7d18d461d0
[2024-01-31T09:17:44.957+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='ledatascientist@ds.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='classification_basic_1' AIRFLOW_CTX_TASK_ID='evaluation' AIRFLOW_CTX_EXECUTION_DATE='2024-01-31T09:17:21.156813+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-31T09:17:21.156813+00:00'
[2024-01-31T09:18:03.994+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/imt/classification_simple_demo/validation_task.py", line 44, in start_evaluation
    model = load(model_path / "model.joblib")
  File "/home/airflow/.local/lib/python3.8/site-packages/joblib/numpy_pickle.py", line 650, in load
    with open(filename, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/models/model.joblib'
[2024-01-31T09:18:04.011+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=classification_basic_1, task_id=evaluation, execution_date=20240131T091721, start_date=20240131T091744, end_date=20240131T091804
[2024-01-31T09:18:04.037+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 23 for task evaluation ([Errno 2] No such file or directory: '/opt/airflow/models/model.joblib'; 768)
[2024-01-31T09:18:04.098+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-01-31T09:18:04.119+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
